[gcp_service_account]
type = "service_account"
project_id = "bionic-cosmos-431620-p3"
private_key_id = "443469c7300847d2bd708d2bf8785a08ad800b90"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDIMK7giZTP93Zk
yrKtHlyXxTl7kBhE4YaTUQ9Qn6/tPLGCmMII87ohAgZ6zPK3oEy1058qC+SK/ljT
TKb45BdtbbDblKhn7y6vYdL1UfXoBWkVUEkdj9+970bycm3MNT5q4PZQu5Cfww/c
EH53fmwE05CSmWJrmC5Z661+onbsDhHo7lOhulRN/koK6Rf4s/SLvK4BkvCjEE9h
jpKAmvqsclUDnwCWe92Fm1fIhQ6DcPsMmHbsjA+pI6+cRpXyh5W3XDat2/P9RPv8
BVNWGlAq7KnKKDoI8/M7kTCupe5U8az9nb36RNsZHa1K21bZ0Kx3jqz2oTdbqxdj
l2sPqZvTAgMBAAECggEAHG7wYmCdgU2i7ufsqYgMG1uzhr2i+iLqIVcRt3V8NamO
239k4oPzkNKf0aX1vL0I3YkkLIL/P/qmP8S9sSYnFFolv4UFclWs1NODyhI3vMUK
oDCvYdfYgzqkDLV8q394e70ItH4fftbkFBvySniV+7gs6urcPsSg+Lvvqsfaijuo
wHnTtPlpTwsHfw89Xo3Mlh9pweE2ISqZ+QPYVPzF4a5dw2ymOgj5g0E+AZBfJoNi
FoDhcAVrZ5xhFXHi5+xFhnloQoH6DLe2SA6xkembxwkvXLWXI6d7Sr7qO8GVro3Q
h8l/+AsaY460MhAdCuFxo1wfbRdMoWhq6sIKD1U90QKBgQD5Wv7OF5U3maCfncLf
DWTOuVraOjC3iO/Qslz0KJ2kj1Bi1onzy9KBHOn7uDApLexKbGOhQSNwIse1tWgP
AH7F5qMAq3rrqIVLPdd852gkIcNYUCzAadvI7YCBrMk+o4EYXXZhCsVGhR+mrnAP
TQAwp9Fhz7k6pPv0eSjboEQfqwKBgQDNhk01I0F+7hfLksLkCzUGouwmAvtdSzUe
InE/yVUlPS8pj+xPdzuJ5C9B+DFOfyIDgvHi+7zLuFiQrIdV2/RUIFzWmOITd/xX
jzlocYYYLgZMBliL/HmUZKXiQxyNg2DRyH+rlg8hU1dVFymHJQHvzZBsyl5kV0cM
wNcstc/seQKBgQCsYWWpH9B+IWxTLALdpCq+ZpESMAwhtT7kbYmpGLLyYkjWKy4v
JgaeT1jKNajFrwOc55VwktFm4gRh78jCJjt9oFWrTuCpLVUIkPX5WRg7ckPTN4nY
ctYH73hZLRPqg6npKCOALqv2dm1NE2ZQjZDGEh3DmpCYpBmyBlhijEbMBQKBgQCf
5Uut+qbbBIt4ss5zMpDnf9tvW0SKeZdywWMQOCfJGAfYMwOrc1zb0648icZ6hohE
6Rwc9rMUX3Bv5fpIfx5gUOlJf5nrgZ7N1Dzal++2YiA+B3XeOuev3nn8RTAynLK3
o2BIcy+EQt2f8qw5Wz5dfbVOHkc/k3NQZbtCKpUAKQKBgQCXbNzg4SFuCM/N8KmG
Azy783nxXSqZHLPScW/Mud4hOS8ioXUX/QMA7f1SyxN6Czve9squwivtGb65I9ev
tmwJnBecSCTcY1REUwz/gIYOG+WDgMTF6+CtW5oO9loreiPE15fk0tDJcJqtFLHe
y74589az3cS+w5Fm2WNaTSdQqg==
-----END PRIVATE KEY-----
"""
client_email = "streamlit-encuesta@bionic-cosmos-431620-p3.iam.gserviceaccount.com"
client_id = "117093784653415070820"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-encuesta%40bionic-cosmos-431620-p3.iam.gserviceaccount.com"
